# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07da1136d4f7f0850addc51a3d8fcd94ef3e1fb2bafac6627d4bde403750bca2bb6634f5dac03610f576606321c222fe26e72b9c5072ff952ec146d4bf3d50d8

test:
  secret_key_base: c7aa642167995207160ea711a4b8cdc70fbbee2cc7b8dd69dc4d4453192ef13d2e62a12e08547793b312d83a286761988834961d58859349687a3f8229fd9b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
